### ISSUE TITLE
Build failure with ubuntu 22.04

### ISSUE THREAD

**Issue by pfultz2** [ROCm/rocMLIR#1415]
There is this failure when migraphx builds with ubuntu 22.04:

```
Traceback (most recent call last):
  File "/usr/local/cget/build/tmp-25313f4698354e8987318405eb382ca9/rocMLIR-bf2911e5245d6452d194ee5dc41c9c2b2869e5c0/external/llvm-project/mlir/lib/Dialect/GPU/AmdDeviceLibsIncGen.py", line 53, in <module>
    generate(Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3:])
  File "/usr/local/cget/build/tmp-25313f4698354e8987318405eb382ca9/rocMLIR-bf2911e5245d6452d194ee5dc41c9c2b2869e5c0/external/llvm-project/mlir/lib/Dialect/GPU/AmdDeviceLibsIncGen.py", line 29, in generate
    with (bcPath / (lib + ".bc")).open("rb") as libFile:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/amdgcn/bitcode/ocml.bc'
```

**Comment by krzysz00** [comment]
Can you take a look at https://github.com/ROCm/rocMLIR/pull/1416 and see if it happens to fix the issue? I'm currently guessing about why you ended up with the error you did, since I don't see `ROCM_PATH` getting set in the Dockerfile, but ... who knows, really?

**Comment by pfultz2** [comment]
So its looking for files in `/usr/amdgcn/` instead of /opt/rocm. I wonder if there is a default ubuntu package that is messing this up. We are pinning the rocm package so it shouldn't install ubuntu's device libs.

**Comment by pfultz2** [comment]
It looks like i added the pin to the wrong dockerfile. Sorry for the noise.
